version: '3.8'
services:
  db_padelu:
    image: postgres:15
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=postgres
    volumes:
      - postgres-data_padelu:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
volumes:
  postgres-data_padelu:
      