version: "3.8"
services:
  postgres_padelu:
    image: postgres:15
    environment:
      - POSTGRES_USER=johndoe
      - POSTGRES_PASSWORD=randompassword
      - POSTGRES_DB=postgres
    volumes:
      - postgres_volume_padelu:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
volumes:
  postgres_volume_padelu:
  name: postgres_volume_padelu
