name: Node.js CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.17.0]
    env:
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      GOOGLE_ID: ${{secrets.GOOGLE_ID}}
      GOOGLE_SECRET: ${{secrets.GOOGLE_SECRET}}
      NEXTAUTH_SECRET: ${{secrets.NEXTAUTH_SECRET}}
      RESEND_API_KEY: ${{secrets.RESEND_API_KEY}}
      RESEND_AUDIENCE_ID: ${{secrets.RESEND_AUDIENCE_ID}}
      STRIPE_SECRET_KEY: ${{secrets.STRIPE_SECRET_KEY}}
      STRIPE_WEBHOOK_SECRET: ${{secrets.STRIPE_WEBHOOK_SECRET}}
      NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}}
      RIOT_API_KEY: ${{secrets.RIOT_API_KEY}}

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install
      - run: pnpm ci
      - run: pnpm run build --if-present
